### ISSUE TITLE
Fix Gallery hover issue

### ISSUE THREAD

**Issue by vchrombie** [scorpion-hut/scorpion-hut.github.io#15]
- The `Next` and `Previous` arrows are not correctly aligned. 
- When you click on `Next` or `Previous` arrows, the gallery sections hovers onto `https://scorpion-hut.github.io/#carousel-1` which doesn't look. Try to fix this.

Please mention what all things are done in your PR also don't forget to refer to this issue.

**Comment by bossbossk20** [comment]
I will do it.
