### ISSUE TITLE
The Menu Bar doesn't close automatically in the mobile version.

### ISSUE THREAD

**Issue by vchrombie** [scorpion-hut/scorpion-hut.github.io#16]
Every time you need to re-tap the Menu Bar to close after you are done with the hovering.

![img](https://image.ibb.co/bBY81z/Screenshot_from_2018_10_02_15_20_26.png)

Try to change the code such that after you tap on any menu item, it hovers onto that element and the menu bar closes automatically.

**Comment by maliMirkec** [comment]
I on it!

**Comment by maliMirkec** [comment]
Done.

See #17.

**Comment by vchrombie** [comment]
@maliMirkec looks great.
Thanks for the contribution. :)

Merging it. :+1:

**Comment by maliMirkec** [comment]
Happy to help!

👍
