### ISSUE TITLE
Menu Bar opens when you tap anything.

### ISSUE THREAD

**Issue by vchrombie** [scorpion-hut/scorpion-hut.github.io#19]
The Menu Bar triggers whatever you tap on the page. Maybe this is because of the PR #17

**Comment by vchrombie** [comment]
@maliMirkec, can you look it?

**Comment by maliMirkec** [comment]
Sure!

**Comment by vchrombie** [comment]
I reverted the PR #17 because the website is under use by the team. Please feel free to drop in a PR after checking it thoroughly.
